name: build-project#Micke

on: 
 push:
 
jobs:
 build-project:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: '9' # specify the .NET version as a string
    
    - name: Build Project
      run: dotnet build todo_demo.sln
  
