name: build-project # Micke

on: 
  push:
    branches:
      - RobinDutt

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: '9' # specify the .NET version as a string
      
      - name: Build Project
        run: dotnet publish todo_demo.sln -c Release -o ./build
      
      - name: List build directory contents
        run: ls -R ./build
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: build-artifact
          path: ./build

  test:
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Check out test
        uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: build-artifact
      
      - name: Test run
        run: dotnet test ./build/todo_demo.dll
